### ISSUE TITLE
AshFrameHandlerTest#testAshFrameData fails continuously

### ISSUE THREAD

**Issue by hanneshofmann** [zsmartsystems/com.zsmartsystems.zigbee#340] opened 2018-07-09 13:00 UTC
With the latest version (1.0.14), the _AshFrameHandlerTest#testAshFrameData_ continuously fails as follows:

`testAshFrameData(com.zsmartsystems.zigbee.dongle.ember.internal.ash.AshFrameHandlerTest)  Time elapsed: 0.008 sec  <<< FAILURE!`

Similar to #333, the test case works locally stable but continuously fails on slow CI machines.

**Comment by cdjackson** [comment] 2018-07-09 13:56
I assume it is the same root cause I explained in the SPI tests. I’ll make the same refactoring.

**Comment by cdjackson** [comment] 2019-02-16 08:29
@hanneshofmann where do we take this? Are you able to provide a PR on the tests, or shall we close this?

**Comment by hanneshofmann** [comment] 2019-02-16 08:56
Sorry, I am not able to provide a PR to improve this test case. I therefore believe we shall better close this.

**Comment by cdjackson** [comment] 2019-02-16 09:06
Ok, thanks. Since this can't be reproduced by me, and I've never seen it fail on CI, I'll close.

**Closed by cdjackson** 2019-02-16 09:06 UTC
Labels: EMBER
